Cache Removal, Cleanup, continue on errors
Added cache removal prior to install.
Clean up / remove previous volatility install in same directory.
Try to continue even if an error is encountered

diff --git a/volatility2-3_install_kali b/volatility2-3_install_kali
--- a/volatility2-3_install_kali
+++ b/volatility2-3_install_kali
@@ -1,1 +1,30 @@
-sudo bash -c 'apt update && apt -y full-upgrade && apt install -y python2 python2-dev python3 python3-dev python3-venv build-essential git libyara-dev yara curl && mkdir -p /opt/volatility2 /opt/volatility3 && curl -s https://bootstrap.pypa.io/pip/2.7/get-pip.py -o /tmp/get-pip.py && python2 /tmp/get-pip.py && git clone https://github.com/volatilityfoundation/volatility.git /opt/volatility2 && python2 -m pip install -U setuptools wheel && python2 -m pip install distorm3==3.4.4 pycrypto pillow openpyxl ujson pytz capstone yara-python==3.7.0 && git clone https://github.com/volatilityfoundation/volatility3.git /opt/volatility3 && python3 -m venv /opt/volatility3/venv && /opt/volatility3/venv/bin/pip install -U pip && ([ -f /opt/volatility3/requirements.txt ] && /opt/volatility3/venv/bin/pip install -r /opt/volatility3/requirements.txt || true) && echo -e "#!/bin/bash\npython2 /opt/volatility2/vol.py \"\$@\"" > /usr/local/bin/vol2 && chmod +x /usr/local/bin/vol2 && echo -e "#!/bin/bash\n/opt/volatility3/venv/bin/python /opt/volatility3/vol.py \"\$@\"" > /usr/local/bin/vol3 && chmod +x /usr/local/bin/vol3 && echo \"Install complete. Use: vol2 | vol3\"'
+sudo bash -c 'set -e;
+rm -rf /var/cache/apt/archives/*;
+rm -rf /var/cache/apt/archives/partial/*;
+# --- SYSTEM DEPS ---
+apt -y full-upgrade;
+apt install -y python2 python2-dev python3 python3-dev python3-venv build-essential git libyara-dev yara curl python3-pefile python3-capstone python3-cryptography python3-lxml python3-jsonschema python3-pillow python3-openpyxl python3-distorm3 python3-yara python3-pycryptodome;
+# -- VOL2 CLEAN UP ---
+rm -rf /opt/volatility2;
+# --- VOL2 INSTALL ---
+mkdir -p /opt/volatility2;
+curl -s https://bootstrap.pypa.io/pip/2.7/get-pip.py -o /tmp/get-pip.py; python2 /tmp/get-pip.py;
+git clone https://github.com/volatilityfoundation/volatility.git /opt/volatility2;
+python2 -m pip install -U setuptools wheel;
+python2 -m pip install distorm3==3.4.4 pycrypto pillow openpyxl ujson pytz capstone yara-python==3.7.0;
+# --- WRAPPER COMMANDS ---
+echo -e "#!/bin/bash\npython2 /opt/volatility2/vol.py \"\$@\"" > /usr/local/bin/vol2; chmod +x /usr/local/bin/vol2;
+echo \"VOLATILITY 2 INSTALLED, USE vol2 TO DO STUFF\";
+# -- VOL3 CLEAN UP ---
+rm -rf /opt/volatility3;
+# --- VOL3 BASE INSTALL ---
+git clone https://github.com/volatilityfoundation/volatility3.git /opt/volatility3; 
+python3 -m venv /opt/volatility3/venv;
+/opt/volatility3/venv/bin/pip install -U pip;
+[ -f /opt/volatility3/requirements.txt ] && /opt/volatility3/venv/bin/pip install -r /opt/volatility3/requirements.txt || true;
+# --- VOL3 OPTIONAL PLUGIN DEPS ---
+/opt/volatility3/venv/bin/pip install pycryptodome capstone yara-python pefile cryptography jsonschema pillow openpyxl lxml;
+# --- WRAPPER COMMANDS ---
+echo -e "#!/bin/bash\n/opt/volatility3/venv/bin/python /opt/volatility3/vol.py \"\$@\"" > /usr/local/bin/vol3; chmod +x /usr/local/bin/vol3;
+echo \"VOLATILITY 3 INSTALLED, USE vol3 TO DO STUFF\";
+'
